#!/usr/local/share/macaroon/bin/python3

# This script decodes and prints a macaroon.
# It uses pymacaroons, which can be installed with:
# yum install python2-pip
# pip install pymacaroons

import sys, os
from pymacaroons import Macaroon

if len(sys.argv) > 1:
    for arg in sys.argv[1:]:
        # Is this argument a filename or a macaroon?
        if os.path.isfile(arg):
            # Filename. Treat the contents as the macaroon.
            with open(arg, 'r') as file:
                data = file.read().rstrip('\n')
            m = Macaroon.deserialize(data)
        else:
            # A literal macaroon.
            m = Macaroon.deserialize(arg)
        print(m.inspect())
else:
    # No arguments provided, let's try to read from stdin.
    for line in sys.stdin:
        m = Macaroon.deserialize(line.rstrip())
        print(m.inspect())
