#!/usr/bin/env python

# This script decodes (or "deserializes") and prints a macaroon.
# It uses pymacaroons, which can be installed on Centos 7 with:
# yum install python2-pip
# pip install pymacaroons

import sys, os, re
from pymacaroons import Macaroon

if len(sys.argv) > 1:
    for arg in sys.argv[1:]:
        # Is this argument a filename or a macaroon?
        if os.path.isfile(arg):
            # Filename. Treat the contents as the macaroon.
            with open(arg, 'r') as file:
                for line in file:
                    # Does this line contain a macaroon?
                    token = re.search("MDA\S*", line)
                    if token:
                        m = Macaroon.deserialize (token.group())
                        print(m.inspect())
        else:
            # A literal macaroon.
            m = Macaroon.deserialize(arg)
            print(m.inspect())
else:
    # No arguments provided, let's try to read from stdin.
    for line in sys.stdin:
        # Does this line contain a macaroon?
        token = re.search("MDA\S*", line)
        if token:
            m = Macaroon.deserialize (token.group())
            print(m.inspect())
